### PR TITLE
Test case for #306

### PR DESCRIPTION
**Pull request by yfei-z**
Here is the test case for the issue that described in #306

### CODE REVIEW

**Comment by jabolina** [comment]
@yfei-z, many thanks for coming up with a reproducer! I've added a commit with a solution.

**Comment by yfei-z** [comment]
I have updated the test, check my comment. Because the timeout might not short enough so although not every time but it can be failed this time.

**Comment by yfei-z** [comment]
I have updated the test, check my comments.

**Comment by jabolina** [comment]
@yfei-z I've added a commit with the changes I had in mind. We only interrupt the voting thread in case the majority is lost. Otherwise, we allow it to stop eventually.

**Comment by yfei-z** [comment]
Seems all good!

**Comment by jabolina** [comment]
Glad to hear it, many thanks, @yfei-z!

**Pull request merged**
